export const SET_PAUSE = 'SET_PAUSE';
export const PLAY_NEXT_TRACK = 'PLAY_NEXT_TRACK';
export const PLAY_PREV_TRACK = 'PLAY_PREV_TRACK';
export const UPDATE_PLAYLIST_AND_PLAY = 'UPDATE_PLAYLIST_AND_PLAY';
export const PLAY_TRACKS = 'PLAY_TRACKS';

export const TOKEN_SET = 'TOKEN_SET';

export const FEATURED_SET = 'FEATURED_SET';

export const GENRES_SET = 'GENRES_SET';

export const PLAYLIST_SET = 'PLAYLIST_SET';

export const VOLUME_CHANGE = 'VOLUME_CHANGE';

export const TRACK_TIME_UPDATE = 'TRACK_TIME_UPDATE';
